// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalGalaxy.DataAccess;

#nullable disable

namespace PortalGalaxy.DataAccess.Migrations
{
    [DbContext(typeof(PortalGalaxyDbContext))]
    partial class PortalGalaxyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalGalaxy.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Alumno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "erick@gmail.com",
                            NombreCompleto = "Erick Velasco"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "juanca@gmail.com",
                            NombreCompleto = "Juan Carlos"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "pepe@gmail.com",
                            NombreCompleto = "Pepe Lucho"
                        },
                        new
                        {
                            Id = 4,
                            Correo = "coco@gmail.com",
                            NombreCompleto = "Coco Perez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
